# AudioMuse-AI Kubernetes Manifest for K3s
# Deploy alongside Navidrome in a K3s cluster
#
# Before deploying:
# 1. Update the secrets with your actual credentials (base64 encoded)
# 2. Update the NAVIDROME_URL in the ConfigMap
# 3. Apply: kubectl apply -f k8s-manifest.yml

---
apiVersion: v1
kind: Namespace
metadata:
  name: audiomuse-ai

---
# Secrets for Navidrome credentials
apiVersion: v1
kind: Secret
metadata:
  name: navidrome-credentials
  namespace: audiomuse-ai
type: Opaque
data:
  # echo -n 'your_username' | base64
  NAVIDROME_USER: YWRtaW4=
  # echo -n 'your_password' | base64
  NAVIDROME_PASSWORD: cGFzc3dvcmQ=

---
# Secrets for PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: audiomuse-ai
type: Opaque
data:
  # echo -n 'audiomuse' | base64
  POSTGRES_USER: YXVkaW9tdXNl
  # echo -n 'audiomusepassword' | base64
  POSTGRES_PASSWORD: YXVkaW9tdXNlcGFzc3dvcmQ=
  # echo -n 'audiomusedb' | base64
  POSTGRES_DB: YXVkaW9tdXNlZGI=

---
# Optional: AI API credentials
apiVersion: v1
kind: Secret
metadata:
  name: ai-credentials
  namespace: audiomuse-ai
type: Opaque
data:
  # echo -n 'your_gemini_api_key' | base64
  GEMINI_API_KEY: ""
  MISTRAL_API_KEY: ""
  OPENAI_API_KEY: ""

---
# ConfigMap for AudioMuse-AI configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: audiomuse-ai-config
  namespace: audiomuse-ai
data:
  # Update this to point to your Navidrome instance
  # Use service name if in same cluster: http://navidrome-service.navidrome:4533
  NAVIDROME_URL: "http://navidrome-service.navidrome:4533"
  MEDIASERVER_TYPE: "navidrome"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  REDIS_URL: "redis://redis-service:6379/0"
  AI_MODEL_PROVIDER: "NONE"
  TEMP_DIR: "/app/temp_audio"

---
# Redis PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: audiomuse-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path

---
# PostgreSQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: audiomuse-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
# Temp audio PVC for Flask
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-audio-flask-pvc
  namespace: audiomuse-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

---
# Temp audio PVC for Worker
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-audio-worker-pvc
  namespace: audiomuse-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: audiomuse-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: audiomuse-ai
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379

---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: audiomuse-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: audiomuse-ai
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
# AudioMuse-AI Flask Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiomuse-ai-flask
  namespace: audiomuse-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiomuse-ai-flask
  template:
    metadata:
      labels:
        app: audiomuse-ai-flask
    spec:
      containers:
        - name: flask
          image: ghcr.io/neptunehub/audiomuse-ai:latest
          ports:
            - containerPort: 8000
          env:
            - name: SERVICE_TYPE
              value: "flask"
            - name: MEDIASERVER_TYPE
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: MEDIASERVER_TYPE
            - name: NAVIDROME_URL
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: NAVIDROME_URL
            - name: NAVIDROME_USER
              valueFrom:
                secretKeyRef:
                  name: navidrome-credentials
                  key: NAVIDROME_USER
            - name: NAVIDROME_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: navidrome-credentials
                  key: NAVIDROME_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: POSTGRES_PORT
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: REDIS_URL
            - name: AI_MODEL_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: AI_MODEL_PROVIDER
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-credentials
                  key: GEMINI_API_KEY
                  optional: true
            - name: TEMP_DIR
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: TEMP_DIR
          volumeMounts:
            - name: temp-audio
              mountPath: /app/temp_audio
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
      volumes:
        - name: temp-audio
          persistentVolumeClaim:
            claimName: temp-audio-flask-pvc

---
# AudioMuse-AI Flask Service
apiVersion: v1
kind: Service
metadata:
  name: audiomuse-ai-service
  namespace: audiomuse-ai
spec:
  selector:
    app: audiomuse-ai-flask
  ports:
    - port: 8000
      targetPort: 8000

---
# AudioMuse-AI Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiomuse-ai-worker
  namespace: audiomuse-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiomuse-ai-worker
  template:
    metadata:
      labels:
        app: audiomuse-ai-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/neptunehub/audiomuse-ai:latest
          env:
            - name: SERVICE_TYPE
              value: "worker"
            - name: MEDIASERVER_TYPE
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: MEDIASERVER_TYPE
            - name: NAVIDROME_URL
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: NAVIDROME_URL
            - name: NAVIDROME_USER
              valueFrom:
                secretKeyRef:
                  name: navidrome-credentials
                  key: NAVIDROME_USER
            - name: NAVIDROME_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: navidrome-credentials
                  key: NAVIDROME_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: POSTGRES_PORT
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: REDIS_URL
            - name: AI_MODEL_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: AI_MODEL_PROVIDER
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-credentials
                  key: GEMINI_API_KEY
                  optional: true
            - name: TEMP_DIR
              valueFrom:
                configMapKeyRef:
                  name: audiomuse-ai-config
                  key: TEMP_DIR
          volumeMounts:
            - name: temp-audio
              mountPath: /app/temp_audio
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
      volumes:
        - name: temp-audio
          persistentVolumeClaim:
            claimName: temp-audio-worker-pvc

---
# Ingress for AudioMuse-AI
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiomuse-ai-ingress
  namespace: audiomuse-ai
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: audiomuse.${SECRET_INTERNAL_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: audiomuse-ai-service
                port:
                  number: 8000
  tls:
    - hosts:
        - audiomuse.${SECRET_INTERNAL_DOMAIN_NAME}
      secretName: audiomuse-ai-tls
